// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LAPTemplateMVC.Models.Configurations;
using LAPTemplateMVC.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace LAPTemplateMVC.Models;

public partial class chatlerContext : DbContext
{
    public chatlerContext(DbContextOptions<chatlerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Chatuser> Chatuser { get; set; }

    public virtual DbSet<Message> Message { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ChatuserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MessageConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
