// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LAPTemplateMVC.Models;
using LAPTemplateMVC.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LAPTemplateMVC.Models.Configurations
{
    public partial class ChatuserConfiguration : IEntityTypeConfiguration<Chatuser>
    {
        public void Configure(EntityTypeBuilder<Chatuser> entity)
        {
            entity.ToTable("CHATUSER", tb =>
                {
                    tb.HasTrigger("TRG_BI_CHATUSER");
                    tb.HasTrigger("TRG_BU_CHATUSER");
                });

            entity.Property(e => e.Valid).HasDefaultValue((short)1);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Chatuser> entity);
    }
}
