// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using LAPTemplateMVC.Models;
using LAPTemplateMVC.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace LAPTemplateMVC.Models.Configurations
{
    public partial class MessageConfiguration : IEntityTypeConfiguration<Message>
    {
        public void Configure(EntityTypeBuilder<Message> entity)
        {
            entity.ToTable("MESSAGE", tb =>
                {
                    tb.HasTrigger("TRG_BI_MESSAGE");
                    tb.HasTrigger("TRG_BU_MESSAGE");
                });

            entity.Property(e => e.Valid).HasDefaultValue((short)1);

            entity.HasOne(d => d.Receiverchatuser).WithMany(p => p.MessageReceiverchatuser)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MESSAGE_RECEIVERCHATUSER");

            entity.HasOne(d => d.Senderchatuser).WithMany(p => p.MessageSenderchatuser)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MESSAGE_SENDERCHATUSER");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Message> entity);
    }
}
