// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LAPTemplateMVC.Models.dboSchema
{
    public partial class ChatuserInsertResult
    {
        [Column("CHATUSERID", TypeName = "decimal(38,0)")]
        public decimal? CHATUSERID { get; set; }
    }
}
