// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using LAPTemplateMVC.Models.dboSchema;


namespace LAPTemplateMVC.Models.dboSchema;

[Table("CHATUSER")]
[Index("Valid", Name = "IX_CHATUSER_VALID", AllDescending = true)]
public partial class Chatuser
{
    [Key]
    [Column("CHATUSERID")]
    public long Chatuserid { get; set; }

    [Required]
    [Column("USERNAME")]
    [StringLength(50)]
    public string Username { get; set; }

    [Required]
    [Column("PUBLICKEY", TypeName = "text")]
    public string Publickey { get; set; }

    [Required]
    [Column("PASSWORDHASH")]
    [StringLength(256)]
    public string Passwordhash { get; set; }

    [Column("CREATEDAT", TypeName = "datetime")]
    public DateTime Createdat { get; set; }

    [Column("VALID")]
    public short Valid { get; set; }

    [Required]
    [Column("MOD_USER")]
    [StringLength(256)]
    public string ModUser { get; set; }

    [Column("MOD_TIMESTAMP", TypeName = "datetime")]
    public DateTime ModTimestamp { get; set; }

    [Required]
    [Column("CR_USER")]
    [StringLength(256)]
    public string CrUser { get; set; }

    [Column("CR_TIMESTAMP", TypeName = "datetime")]
    public DateTime CrTimestamp { get; set; }

    [InverseProperty("Receiverchatuser")]
    public virtual ICollection<Message> MessageReceiverchatuser { get; set; } = new List<Message>();

    [InverseProperty("Senderchatuser")]
    public virtual ICollection<Message> MessageSenderchatuser { get; set; } = new List<Message>();
}